### ISSUE TITLE
Tengo un error al hacer el pull

### ISSUE THREAD

**Issue by HenryG96** [DiegoNM95/PRG-3#1]
me dice que Auto-merging src/miembroscolegio/Alumno.java
CONFLICT (content): Merge conflict in src/miembroscolegio/Alumno.java
Automatic merge failed; fix conflicts and then commit the result.

y cuando le doy git status me dice:
On branch master
**Your branch and 'origin/master' have diverged,**
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

       ` _**both modified:   src/miembroscolegio/Alumno.java**_`

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by ludmartinez** [comment]
Ya está resuelto el problema de tu parte. Solo falta de la parte de Cesar

**Comment by HenryG96** [comment]
si ya estamos! #
